### ISSUE TITLE
Install not working / SOLVED with solution for others

### ISSUE THREAD

**Issue by bradandrews4** [annularis/shop#2]
Hi I've been messing around with the code but I'm a little confused by how to get the installer script to work?...

It seems to always fail with the composer thing. Firstly it seems this repo hasn't even included a composer file however even if I use the original bitwasp one the install script just tells me to press F5 once I have installed and run the composer command. All the other commands like setting file permissions works fine its just the composer that even after its ran the installer script seems to think it hasn't done so.

I've considered just adding the information into the config file manually at this point but I want to figure out exactly what's causing this to not work in the first place.

Is there a recommended OS or anything of that nature that could help me?
Also unrelated question, for the bitcoin RPC username password etc does it have to be from the bitcoin core? 

Or could one use ElectrumX or something along those lines? Primarily asking that as bitcoin requires you download the full blockchain whereas I am told Electrum does not?

Cheers

**Comment by bradandrews4** [comment]
@serhack any suggestions?

I have everything setup and running including bitcoin node but when I click install the only error message displayed is this:

"Not all fields have been filled in correctly."

I can assure you every single field has been filled out correctly!

What can you recommend to at the very least figure out where the issue is coming from?

**Comment by serhack** [comment]
Hey,
sorry for delay. Github made a mess with notifications. Have you already installed composer?

This project is going to be a dead project, the legendary developers are working on a store only with monero!
http://geocrypto.io

**Comment by bradandrews4** [comment]
Yes composer is installed everything is done correctly to the point where it asks me for the config information and has the install button.


It's here where I get the error message.


I think the error has something to do with the bitcoin core daemon. I originally thought that its firewall could be acting up blocking port 8332 or something. I did have my host confirm to me that port 8332 was open however.


I've tested the install even under localhost (doing a curl to the 8332 port with localhost worked so I assumed maybe 8332 was only open to localhost or something) but that gave the same error.


What confuses me is there is an actual defined error for if the issue is with bitcoin core so the error message I'm getting suggests the error is elsewhere?


Is there anything you can suggest to get this working? geocrypto looks amazing but almost a bit too fancy for me and also monero is great but I don't think I want to accept just monero with btc having such a market dominance I feel I'd loose too many potential customers and merchants as a direct result.


I hope you can help assist!

Regards,

All the best!


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by bradandrews4** [comment]
@serhack 
I can confirm its not to do with the bitcoin core in anyway now...

I have loaded a test script onto my server basically using easy-bitcoin simply to test to see if RPC connections to the bitcoind server are working correctly.

I am able to connect using the configured RPC user and Pass and then also issue commands such as $bitcoin->getblockcount(); which matches up with the blockcount advertised on public blockchains like blockchain.info

This confirms the error lies within the install script. That further explains why the error message displayed doesn't explain anything and simply says "Not all fields have been filled in correctly." when there is a specific field for if the bitcoin daemon isn't connecting.

What could possibly be causing this to not install?

Mysql is setup and database was created and definitely entered the info correctly so not sure what more I can do?

Thanks

**Comment by serhack** [comment]
Can you re-try now?

**Comment by bradandrews4** [comment]
@serhack 

Thanks I'm retrying now.
 
I deleted all files for a fresh start but ran into same initial problem as I did when I started out. 

Your install page requires composer at the end but you haven't included composer.json in the root of the library. 

Theres only one .json file and thats for the smarty library which I assume is not what composer is needed for so I grabbed the composer.json from the original bitwasp project and ran that..

Will update on if your update on the install page + new install of this worked but as a heads up you need to either add your own, edit or just simply add the original composer.json file to make it easier for everybody to install this project (Y) 

Thanks :)

**Comment by bradandrews4** [comment]
Hey man @serhack  it all worked great as far as getting the install script to work!

I noticed it still said bitwas in a few remedial places but obviously that's not a big deal. 
What I'm now encountering however is a big error printed on the index page essentially making the site currently useless.

What's your opinion on the error code?

`An uncaught Exception was encountered

Type: UnexpectedValueException

Message: Session: Configured driver 'cookie' was not found. Aborting.

Filename: /var/www/html/BitWasp/shop-master/system/libraries/Session/Session.php

Line Number: 233

Backtrace:

File: /var/www/html/BitWasp/shop-master/application/core/MY_Controller.php
Line: 27
Function: __construct

File: /var/www/html/BitWasp/shop-master/application/controllers/Welcome.php
Line: 37
Function: __construct

File: /var/www/html/BitWasp/shop-master/index.php
Line: 282
Function: require_once`

**Comment by bradandrews4** [comment]
Hey man you must be pretty busy with this project, seems you're doing it all alone so let me tell you what I've done so far to get it working!

It's certainly far from safe or a production ready environment nor do I even know what I deactivated really etc but this is what is needed in order to get a working version of the market!

Also as a quick side note there is issues within the code where it assumes the directory you are working from within. This just makes certain things a massive pain!

For example the install script where it gives you the commands to feed into the terminal.
There it automatically assumes you're working from inside a directory within the market so if you do it from the root directory you get errors that the files don't exist.

To fix that issue was easy enough I just changed directory to the install folder inside my terminal and issued the commands from there and all was a success.

Then I had to change directory again back into the root so I could run the final command which was composer.

There I found there was no composer.json included with the files. To resolve that issue I just grabbed the latest composer.json from the master branch of the original BitWasp git.

There was a problem with the install script itself which I'm not sure what it was but after you commited some changes and requested I try it again I proceeded by doing a fresh install by cloning the git again and repeating the above steps.

That's when I got the new errors I pasted above. Something to do with Cookie

To fix that issue I needed to edit the
application/config/config.php file.

I commented out the line simply adding the obvious // to:
`$config['sess_driver']	= 'cookie';`

However before figuring out that fix I first noticed there were more files missing upon doing some more research into the error... Inside:
"system/libraries/session/drivers"

There were a couple cookie related driver files that were in the original BitWasp but not here. I proceeded to upload them to the relevant directory.

After all that was done and I refreshed I was greeted with my final bunch of errors.

These were all pretty confusing and honestly I should have taken a picture or copied them out or something though I'm sure you can get them repeating the steps... Either way it seemed obvious the errors were permissions related. Wasn't able to affect them by chmoding the files I thought were to blame so the eventual work around was of course the last resort...

I had to chmod 777 the entire shop-master directory recursivly. 

Obviously (and for anyone reading this trying to get a working setup who may not know) the command to do that from within the terminal which is 100000x times faster than doing it through FTP) is:
`chmod -R 777 .`

With all that done it seems I have managed to get to the main login screen.

I faced one last problem with this though not a major one. 

I set this up on two servers. One was a plain VPS which had no FQDM only an IP and all successful and worked no problem.

The other was a VPS also but hosting VestaCP with a couple different clients essentially on a shared hosting plan. Now I pointed used a subdomain on my FQDN to host the content however it seems that when I go to the site on that server all the links internally are for some reason attempting to go to the server IP instead of to the domain that's being used.

The issue with that is http://123.455.642/shop-master/assets/js/bootstrap.js or w.e doesn't exist on the server.
The full path would need to be 
http://123.455.642/home/admin/web/subdom.fqdn.com/public_html/shop-master/assets/js/bootstrap.js and even if I try accessing that link it doesn't work because the webserver isn't configured like that so you just get a 404...
Realistically the site should just be using whatever the url the user is coming from for it.

That way it would try to pull the js and css files etc from
http://subdom.fqdn.com/shop-master/assets/js/bootstrap.js and that file does exist and works just fine!

But rather than going through all the code myself and hardcode the correct fqdn or basedir I will just work on the 2nd server as its just for a development environment. 

Would love to see this project grow! Really sad to hear you're thinking of abandoning it! 

Thanks for your assistance in getting this up and running and getting it this far! :) 👍

**Comment by serhack** [comment]
I Will upload the solutions.

**Comment by danfossi** [comment]
> I commented out the line simply adding the obvious // to: `$config['sess_driver'] = 'cookie';`
Same problem here and same fix but I think this creates problems by trying to log in with non-administrative users.

> I had to chmod 777 the entire shop-master directory recursivly.
@bradandrews4 have you changed the owner of shop dir ? I've had the same problem and solved it with:
`chown www-data:www-data /var/www/html/shop -Rv`
