### ISSUE TITLE
Unable to upload product image

### ISSUE THREAD

**Issue by jvli0** [annularis/shop#25]
Tried with both JPG and PNG. It returns _The filetype you are attempting to upload is not allowed._

**Comment by serhack** [comment]
Strange, I can in my "demo" store.

**Comment by danfossi** [comment]
I can, too!

Can you try to upload this: http://cdn1.bigcommerce.com/server1700/b627b/products/1440/images/1814/toy-hand-grenade-1__72164.1302741752.800.800.jpg ?

**Comment by jvli0** [comment]
@danfossi yep it works with that one. Not with this one: http://d3gqasl9vmjfd8.cloudfront.net/9832600f-42ad-45b3-9e63-4d01f5916911.jpg 

Maybe just a corrupt image from google.

**Comment by danfossi** [comment]
Fine, I've tried some gif and checked that exif are removed, all works fine! Do some other random upload and if it work we can close the issue.

**Comment by jvli0** [comment]
It works, my bad.
