### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by lorexx** [annularis/shop#42]
hello all members of github i'm newbie here, can anyone explain me please step by step how to install and test it please ?
I like to testing on sample server before starting and improve my knowledge about this script.
i can pay for the lesson, please.

The best regards !   Telegram: https://t.me/lilzzi

**Comment by danfossi** [comment]
Hi @lorexx ,
what operating system are you using? have you have read the install.md ?

Telegram: https://t.me/danfossi

**Comment by lorexx** [comment]
Hi @danfossi !
Thanks so much for the fast answer, i have try to write you on telegram , but my profile have anti spam active :/ i don't know the reason..
You have Skype or Icq, please ?

The best regards !
