### ISSUE TITLE
Price Index

### ISSUE THREAD

**Issue by danfossi** [annularis/shop#51]
The Bitcoinaverage service changed the use of the APIs and also the URL.

--
The address:
`https://api.bitcoinaverage.com/all` 
no longer exists!

--
File: [application/config/bitcoin_index.php]
File: [application/libraries/Bw_bitcoin.php]

We need to change price index provider or modify the function.

--
Refer to: https://apiv2.bitcoinaverage.com/

**Comment by serhack** [comment]
We have to edit everything for Monero.

**Comment by serhack** [comment]
See #52
